import type { NextPage } from 'next'
import Head from 'next/head'
import AppBar from '../components/AppBar'
import CompanyInfos from '../components/CompanyInfos'
import Contact from '../components/Contact'
import Hero from '../components/Hero'
import Services from '../components/Services'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next Appi</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <AppBar />
      <Hero />
      <CompanyInfos />
      <Services />
      <Contact />
    </>
  )
}

export default Home
